version: '3'

networks:
  backend:
    external:
      name: service_backend

services:
  oauth:
    restart: always
    container_name: oauth
    build:
      context: ./
      dockerfile: ./configs/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - NCU_OAUTH_CLIENT_ID=${NCU_OAUTH_CLIENT_ID}
      - NCU_OAUTH_CLIENT_SECRET=${NCU_OAUTH_CLIENT_SECRET}
      - OAUTH_GRANTS=${OAUTH_GRANTS}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_SALT=${SERVER_SALT}
    networks:
      - backend